CREATE TABLE IF NOT EXISTS reading_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    cadence VARCHAR(16) NOT NULL,
    target_minutes INTEGER NOT NULL DEFAULT 0,
    target_pages INTEGER NOT NULL DEFAULT 0,
    reminder_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    quiet_hours VARCHAR(64),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reading_goals_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_reading_goals_user_cadence UNIQUE (user_id, cadence)
);

CREATE TABLE IF NOT EXISTS book_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id VARCHAR(128) NOT NULL,
    percent_complete INTEGER NOT NULL DEFAULT 0,
    chapters_completed INTEGER NOT NULL DEFAULT 0,
    minutes_read INTEGER NOT NULL DEFAULT 0,
    current_shelf VARCHAR(32) NOT NULL DEFAULT 'TO_READ',
    last_read_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_book_progress_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_book_progress_user_book UNIQUE (user_id, book_id),
    CONSTRAINT chk_book_progress_percent CHECK (percent_complete BETWEEN 0 AND 100),
    CONSTRAINT chk_book_progress_minutes CHECK (minutes_read >= 0),
    CONSTRAINT chk_book_progress_chapters CHECK (chapters_completed >= 0)
);

CREATE TABLE IF NOT EXISTS annotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id VARCHAR(128) NOT NULL,
    annotation_type VARCHAR(16) NOT NULL,
    content VARCHAR(4000),
    chapter_label VARCHAR(160),
    page_ref VARCHAR(64),
    visibility VARCHAR(16) NOT NULL DEFAULT 'PRIVATE',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_annotations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS social_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    friend_user_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'FOLLOWING',
    visibility VARCHAR(16) NOT NULL DEFAULT 'FRIENDS',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_social_connections_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_social_connections_friend FOREIGN KEY (friend_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_social_connections_pair UNIQUE (user_id, friend_user_id)
);

CREATE TABLE IF NOT EXISTS activity_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    book_id VARCHAR(128),
    detail VARCHAR(2000),
    visibility VARCHAR(16) NOT NULL DEFAULT 'FRIENDS',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS book_clubs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(2000),
    invite_code VARCHAR(64) NOT NULL UNIQUE,
    moderation_level VARCHAR(32) NOT NULL DEFAULT 'OWNER_ONLY',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_book_clubs_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS book_club_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'MEMBER',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_book_club_memberships_club FOREIGN KEY (club_id) REFERENCES book_clubs(id) ON DELETE CASCADE,
    CONSTRAINT fk_book_club_memberships_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_book_club_memberships UNIQUE (club_id, user_id)
);

CREATE TABLE IF NOT EXISTS discussion_threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL,
    book_id VARCHAR(128),
    chapter_ref VARCHAR(160),
    title VARCHAR(240) NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_discussion_threads_club FOREIGN KEY (club_id) REFERENCES book_clubs(id) ON DELETE CASCADE,
    CONSTRAINT fk_discussion_threads_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS discussion_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    message VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_discussion_posts_thread FOREIGN KEY (thread_id) REFERENCES discussion_threads(id) ON DELETE CASCADE,
    CONSTRAINT fk_discussion_posts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS list_collaborators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    permission VARCHAR(16) NOT NULL DEFAULT 'EDITOR',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_list_collaborators_list FOREIGN KEY (list_id) REFERENCES lists(id) ON DELETE CASCADE,
    CONSTRAINT fk_list_collaborators_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_list_collaborators UNIQUE (list_id, user_id)
);

CREATE TABLE IF NOT EXISTS review_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_helpful BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_votes_review FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_votes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_review_votes UNIQUE (review_id, user_id)
);

CREATE TABLE IF NOT EXISTS review_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_reports_review FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_reports_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notification_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    goal_reminders BOOLEAN NOT NULL DEFAULT TRUE,
    book_club_replies BOOLEAN NOT NULL DEFAULT TRUE,
    friend_activity BOOLEAN NOT NULL DEFAULT TRUE,
    quiet_hours VARCHAR(64),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_preferences_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS custom_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    title VARCHAR(240) NOT NULL,
    authors VARCHAR(240),
    isbn VARCHAR(32),
    description VARCHAR(4000),
    external_ref VARCHAR(240),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_custom_books_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    imported_count INTEGER NOT NULL DEFAULT 0,
    deduplicated_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_import_jobs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reading_goals_user_id ON reading_goals (user_id);
CREATE INDEX IF NOT EXISTS idx_book_progress_user_id ON book_progress (user_id);
CREATE INDEX IF NOT EXISTS idx_annotations_user_id ON annotations (user_id);
CREATE INDEX IF NOT EXISTS idx_social_connections_user_id ON social_connections (user_id);
CREATE INDEX IF NOT EXISTS idx_activity_events_user_id ON activity_events (user_id);
CREATE INDEX IF NOT EXISTS idx_activity_events_created_at ON activity_events (created_at);
CREATE INDEX IF NOT EXISTS idx_book_clubs_owner_user_id ON book_clubs (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_book_club_memberships_club_id ON book_club_memberships (club_id);
CREATE INDEX IF NOT EXISTS idx_book_club_memberships_user_id ON book_club_memberships (user_id);
CREATE INDEX IF NOT EXISTS idx_discussion_threads_club_id ON discussion_threads (club_id);
CREATE INDEX IF NOT EXISTS idx_discussion_posts_thread_id ON discussion_posts (thread_id);
CREATE INDEX IF NOT EXISTS idx_list_collaborators_list_id ON list_collaborators (list_id);
CREATE INDEX IF NOT EXISTS idx_review_votes_review_id ON review_votes (review_id);
CREATE INDEX IF NOT EXISTS idx_review_reports_review_id ON review_reports (review_id);
CREATE INDEX IF NOT EXISTS idx_custom_books_user_id ON custom_books (user_id);
CREATE INDEX IF NOT EXISTS idx_import_jobs_user_id ON import_jobs (user_id);
